// <auto-generated />
using DOGobj.InfrastructureServices.Gateways.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManagementOrganizations.WebService.Migrations
{
    [DbContext(typeof(DOGobjContext))]
    [Migration("20200519161209_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("DOGobj.DomainObjects.DOGobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentalAffiliation")
                        .HasColumnType("TEXT");

                    b.Property<string>("FencingSite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Landmark")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformLighting")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteElements")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DOGobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DepartmentalAffiliation = "Департамент культуры города Москвы",
                            FencingSite = "да",
                            Landmark = "город Москва, Рублёвское шоссе, дом 26, корпус 4",
                            PlatformLighting = "нет",
                            SiteElements = "балансир для собак,барьер одинарный,бум для собак,вышка-лестница (с перилами),скамья для собаководов,трамплин,тренировочный снаряд с покрышкой,урна"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
